-- ----------------------------
-- MES 编码规则表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_md_auto_code_rule" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(64) NOT NULL,
    "description" varchar(255) DEFAULT NULL,
    "max_length" int DEFAULT NULL,
    "padded" bit NOT NULL DEFAULT FALSE,
    "padded_char" varchar(1) DEFAULT NULL,
    "padded_method" tinyint DEFAULT NULL,
    "status" tinyint NOT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- MES 编码规则组成表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_md_auto_code_part" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rule_id" bigint NOT NULL,
    "sort" int NOT NULL,
    "type" tinyint NOT NULL,
    "length" int NOT NULL,
    "date_format" varchar(20) DEFAULT NULL,
    "fix_character" varchar(64) DEFAULT NULL,
    "serial_start_no" int DEFAULT NULL,
    "serial_step" int DEFAULT NULL,
    "cycle_flag" bit DEFAULT FALSE,
    "cycle_method" tinyint DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- MES 编码生成记录表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_md_auto_code_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rule_id" bigint NOT NULL,
    "result" varchar(64) DEFAULT NULL,
    "serial_no" bigint DEFAULT NULL,
    "input_char" varchar(64) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
