-- ----------------------------
-- MES 编码规则表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_md_auto_code_rule" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(64) NOT NULL,
    "description" varchar(255) DEFAULT NULL,
    "max_length" int DEFAULT NULL,
    "padded" bit NOT NULL DEFAULT FALSE,
    "padded_char" varchar(1) DEFAULT NULL,
    "padded_method" tinyint DEFAULT NULL,
    "status" tinyint NOT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- MES 编码规则组成表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_md_auto_code_part" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rule_id" bigint NOT NULL,
    "sort" int NOT NULL,
    "type" tinyint NOT NULL,
    "length" int NOT NULL,
    "date_format" varchar(20) DEFAULT NULL,
    "fix_character" varchar(64) DEFAULT NULL,
    "serial_start_no" int DEFAULT NULL,
    "serial_step" int DEFAULT NULL,
    "cycle_flag" bit DEFAULT FALSE,
    "cycle_method" tinyint DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- MES 编码生成记录表
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_md_auto_code_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rule_id" bigint NOT NULL,
    "result" varchar(64) DEFAULT NULL,
    "serial_no" bigint DEFAULT NULL,
    "input_char" varchar(64) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- MES 到货通知单
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_wm_arrival_notice" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) DEFAULT NULL,
    "name" varchar(255) DEFAULT NULL,
    "purchase_order_code" varchar(64) DEFAULT NULL,
    "vendor_id" bigint DEFAULT NULL,
    "arrival_date" timestamp DEFAULT NULL,
    "contact_name" varchar(64) DEFAULT NULL,
    "contact_telephone" varchar(64) DEFAULT NULL,
    "status" tinyint DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- MES 外协入库单
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_wm_outsource_receipt" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) DEFAULT NULL,
    "name" varchar(255) DEFAULT NULL,
    "work_order_id" bigint DEFAULT NULL,
    "vendor_id" bigint DEFAULT NULL,
    "receipt_date" timestamp DEFAULT NULL,
    "status" tinyint DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- MES 来料检验单（IQC）
-- ----------------------------
CREATE TABLE IF NOT EXISTS "mes_qc_iqc" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) DEFAULT NULL,
    "name" varchar(255) DEFAULT NULL,
    "template_id" bigint DEFAULT NULL,
    "source_doc_type" int DEFAULT NULL,
    "source_doc_id" bigint DEFAULT NULL,
    "source_line_id" bigint DEFAULT NULL,
    "vendor_id" bigint DEFAULT NULL,
    "vendor_batch" varchar(64) DEFAULT NULL,
    "item_id" bigint DEFAULT NULL,
    "received_quantity" decimal(24,6) DEFAULT NULL,
    "check_quantity" decimal(24,6) DEFAULT NULL,
    "qualified_quantity" decimal(24,6) DEFAULT NULL,
    "unqualified_quantity" decimal(24,6) DEFAULT NULL,
    "critical_rate" decimal(10,2) DEFAULT NULL,
    "major_rate" decimal(10,2) DEFAULT NULL,
    "minor_rate" decimal(10,2) DEFAULT NULL,
    "critical_quantity" int DEFAULT NULL,
    "major_quantity" int DEFAULT NULL,
    "minor_quantity" int DEFAULT NULL,
    "check_result" tinyint DEFAULT NULL,
    "receive_date" timestamp DEFAULT NULL,
    "inspect_date" timestamp DEFAULT NULL,
    "inspector_user_id" bigint DEFAULT NULL,
    "status" tinyint DEFAULT NULL,
    "remark" varchar(500) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
