name: yudao-ui-admin CI

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

env:
  TZ: Asia/Shanghai
  WORK_DIR: yudao-ui-admin

defaults:
  run:
    shell: bash
    working-directory: yudao-ui-admin

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install dependencies
        run: |
          node --version
          yarn --version
          yarn install --frozen-lockfile

      - name: Build
        run: yarn build:prod
